import { BatchWriteItemOutput as AWSBatchWriteItemOutput, BatchGetItemOutput as AWSBatchGetItemOutput, QueryOutput as AWSQueryOutput, ScanOutput as AWSScanOutput, Capacity as AWSCapacity, ConsumedCapacity as AWSConsumedCapacity } from '@aws-sdk/client-dynamodb';
export declare function mergeItemCollectionMetrics(responses: AWSBatchWriteItemOutput[], tableName: string): import("@aws-sdk/client-dynamodb").ItemCollectionMetrics[];
export declare function mergeBatchDeleteUnprocessedKeys(responses: AWSBatchWriteItemOutput[], tableName: string): Record<string, import("@aws-sdk/client-dynamodb").AttributeValue>[];
export declare function mergeBatchGetUnprocessedKeys(responses: AWSBatchGetItemOutput[], tableName: string): Record<string, import("@aws-sdk/client-dynamodb").AttributeValue>[];
export declare function mergeBatchPutUnprocessedItems(responses: AWSBatchWriteItemOutput[], tableName: string): Record<string, import("@aws-sdk/client-dynamodb").AttributeValue>[];
export declare function mergeBatchGetConsumedCapacities(responses: AWSBatchGetItemOutput[], tableName: string): AWSConsumedCapacity;
export declare function mergeBatchWriteConsumedCapacities(responses: AWSBatchWriteItemOutput[], tableName: string): AWSConsumedCapacity;
export declare function mergeQueryConsumedCapacities(responses: AWSQueryOutput[], tableName: string): AWSConsumedCapacity;
export declare function mergeScanConsumedCapacities(responses: AWSScanOutput[], tableName: string): AWSConsumedCapacity;
export declare function mergeConsumedCapacities(consumedCapacities: AWSConsumedCapacity[], tableName: string): AWSConsumedCapacity;
export declare function mergeConsumedCapacityTable(consumedCapacities: AWSConsumedCapacity[]): AWSCapacity;
export declare function mergeTableCapacity(tableCapacities: AWSCapacity[]): AWSCapacity;
export declare function mergeGlobalSecondaryIndexes(consumedCapacities: AWSConsumedCapacity[]): Record<string, AWSCapacity>;
export declare function mergeLocalSecondaryIndexes(consumedCapacities: AWSConsumedCapacity[]): Record<string, AWSCapacity>;
export declare function mergeSecondaryIndexes(indexesList: AWSConsumedCapacity[]): Record<string, AWSCapacity>;
